// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCupJWcY-mAK0-gXdGrMmPRJjK4HbB6ACY',
    appId: '1:207908644903:web:18fb6d2178c9f0db830602',
    messagingSenderId: '207908644903',
    projectId: 'campus-lost-and-found-e960e',
    authDomain: 'campus-lost-and-found-e960e.firebaseapp.com',
    storageBucket: 'campus-lost-and-found-e960e.firebasestorage.app',
    measurementId: 'G-JCD97JYT8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_JN_-3klIns8vePjU4ZT7k9HwZGAo7c4',
    appId: '1:207908644903:android:3990a101ba5d7fbc830602',
    messagingSenderId: '207908644903',
    projectId: 'campus-lost-and-found-e960e',
    storageBucket: 'campus-lost-and-found-e960e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRzff-X6dkiOPujcu9lxZWXsv2-8YeZuE',
    appId: '1:207908644903:ios:3bd373a07b996f12830602',
    messagingSenderId: '207908644903',
    projectId: 'campus-lost-and-found-e960e',
    storageBucket: 'campus-lost-and-found-e960e.firebasestorage.app',
    iosClientId: '207908644903-lfp60dg2hbu9cupe5nbq5mcb114moebc.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusLostFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRzff-X6dkiOPujcu9lxZWXsv2-8YeZuE',
    appId: '1:207908644903:ios:3bd373a07b996f12830602',
    messagingSenderId: '207908644903',
    projectId: 'campus-lost-and-found-e960e',
    storageBucket: 'campus-lost-and-found-e960e.firebasestorage.app',
    iosClientId: '207908644903-lfp60dg2hbu9cupe5nbq5mcb114moebc.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusLostFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCupJWcY-mAK0-gXdGrMmPRJjK4HbB6ACY',
    appId: '1:207908644903:web:71a4d06159fbc8db830602',
    messagingSenderId: '207908644903',
    projectId: 'campus-lost-and-found-e960e',
    authDomain: 'campus-lost-and-found-e960e.firebaseapp.com',
    storageBucket: 'campus-lost-and-found-e960e.firebasestorage.app',
    measurementId: 'G-CP8HSWBHZB',
  );
}
